// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.demo.sa.domian;

import com.demo.sa.domian.Amphur;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Amphur_Roo_Configurable {
    
    declare @type: Amphur: @Configurable;
    
}
