// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.demo.sa.domian;

import com.demo.sa.domian.Province;

privileged aspect Province_Roo_JavaBean {
    
    public String Province.getName() {
        return this.name;
    }
    
    public void Province.setName(String name) {
        this.name = name;
    }
    
}
